#### TP 1 : Preprocessing et Pipeline

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures, MinMaxScaler, OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
import seaborn as sns

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)


In [3]:
# Charger le dataset depuis Seaborn
df = sns.load_dataset("diamonds")

# Afficher les 5 premières lignes
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


### Train Test Split

In [4]:
train_set, test_set = train_test_split(df,test_size=0.2, random_state=0)

In [5]:
print("train_set :",train_set.shape)
print("test_set :",test_set.shape)

train_set : (43152, 10)
test_set : (10788, 10)


### Encoding
Commencez par explorer votre jeu de données et identifiez les variables catégoriques.<br>
Choisissez ensuite entre OrdinalEncoder et OneHotEncoder pour encoder ces variables : <br>
    - Si les catégories suivent un ordre naturel (ex. : "petit", "moyen", "grand"), utilisez OrdinalEncoder.<br>
    - Si elles n'ont pas d'ordre particulier (ex. : "rouge", "bleu", "vert"), utilisez OneHotEncoder.<br>
    - Faites une recherche sur Internet sur la classification des diamants afin de déterminer la méthode d'encodage la plus appropriée.

In [6]:
# Déterminer les différentes valeurs qui se cachent dans la première colonne catégorielle
valeurs_cut = train_set["cut"].unique()
print(valeurs_cut)

['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']


In [7]:
# Déterminer les différentes valeurs qui se cachent dans la deuxième colonne catégorielle
valeurs_color = train_set["color"].unique()
print(valeurs_color)

['G', 'E', 'H', 'D', 'F', 'I', 'J']
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']


In [8]:
# Déterminer les différentes valeurs qui se cachent dans  la troisième colonne catégorielle
valeurs_clarity = train_set["clarity"].unique()
print(valeurs_clarity)

['VS1', 'VS2', 'VVS2', 'SI1', 'IF', 'VVS1', 'SI2', 'I1']
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']


In [9]:
#A l'aide d'une petite recherche sur internet, spécifiez l'ordre de chaque catégorie

cut_order = ["Fair", "Good", "Very Good", "Premium", "Ideal"]
color_order = ["J","I","H","G","F","E","D"]
clarity_order = ["I1","SI2","SI1","VS2","VS1","VVS2","VVS1","IF"]

#Introduire cut_order color_order dans l'Encoder

encoder = OrdinalEncoder(categories=[cut_order, color_order, clarity_order])

encoding_results = encoder.fit_transform(train_set[["cut","color","clarity"]])

encoding_results

array([[4., 3., 4.],
       [4., 3., 3.],
       [4., 5., 5.],
       ...,
       [3., 1., 4.],
       [4., 3., 7.],
       [4., 4., 1.]])

In [10]:
train_set

,carat,cut,color,clarity,depth,table,price,x,y,z
26250,1.63,Ideal,G,VS1,61.7,55.0,15697,7.56,7.60,4.68
31510,0.34,Ideal,G,VS2,62.2,57.0,765,4.47,4.44,2.77
40698,0.40,Ideal,E,VVS2,61.7,56.0,1158,4.73,4.77,2.93
42634,0.58,Premium,H,SI1,62.1,55.0,1332,5.38,5.35,3.33
47714,0.63,Very Good,D,SI1,62.8,57.0,1885,5.40,5.46,3.41
...,...,...,...,...,...,...,...,...,...,...
45891,0.52,Premium,F,VS2,60.7,59.0,1720,5.18,5.14,3.13
52416,0.70,Good,D,SI1,63.6,60.0,2512,5.59,5.51,3.51
42613,0.32,Premium,I,VS1,61.3,58.0,505,4.35,4.39,2.68
43567,0.41,Ideal,G,IF,61.0,57.0,1431,4.81,4.79,2.93


In [11]:
#injecter le résultat de l'encodage dans le tableau de trainset

train_set[["cut","color","clarity"]] = encoding_results
train_set

,carat,cut,color,clarity,depth,table,price,x,y,z
26250,1.63,4.0,3.0,4.0,61.7,55.0,15697,7.56,7.60,4.68
31510,0.34,4.0,3.0,3.0,62.2,57.0,765,4.47,4.44,2.77
40698,0.40,4.0,5.0,5.0,61.7,56.0,1158,4.73,4.77,2.93
42634,0.58,3.0,2.0,2.0,62.1,55.0,1332,5.38,5.35,3.33
47714,0.63,2.0,6.0,2.0,62.8,57.0,1885,5.40,5.46,3.41
...,...,...,...,...,...,...,...,...,...,...
45891,0.52,3.0,4.0,3.0,60.7,59.0,1720,5.18,5.14,3.13
52416,0.70,1.0,6.0,2.0,63.6,60.0,2512,5.59,5.51,3.51
42613,0.32,3.0,1.0,4.0,61.3,58.0,505,4.35,4.39,2.68
43567,0.41,4.0,3.0,7.0,61.0,57.0,1431,4.81,4.79,2.93


### Normalisation

In [12]:
scaler=MinMaxScaler()
train_set = scaler.fit_transform(train_set)
train_set

array([[0.2972973 , 1.        , 0.5       , ..., 0.70391061, 0.12903226,
        0.14716981],
       [0.02910603, 1.        , 0.5       , ..., 0.41620112, 0.075382  ,
        0.08710692],
       [0.04158004, 1.        , 0.83333333, ..., 0.44040968, 0.08098472,
        0.09213836],
       ...,
       [0.02494802, 0.75      , 0.16666667, ..., 0.40502793, 0.07453311,
        0.08427673],
       [0.04365904, 1.        , 0.5       , ..., 0.44785847, 0.08132428,
        0.09213836],
       [0.14760915, 1.        , 0.66666667, ..., 0.58100559, 0.10509338,
        0.11949686]])

### Transformation du test set

In [13]:
encoding_results = encoder.fit_transform(test_set[["cut","color","clarity"]])

In [14]:
#injecter le résultat de l'encodage dans le tableau de testset
test_set[["cut","color","clarity"]]=encoding_results 

### Simplifier le tout avec une Pipeline

In [15]:
from sklearn.pipeline import Pipeline, make_pipeline

In [16]:
df = sns.load_dataset("diamonds")
df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [17]:
train_set, test_set = train_test_split(df,test_size=0.2,random_state=0)

In [18]:
pipeline = Pipeline(steps=[("Encoder",OrdinalEncoder()),
                           ("Normaliser",MinMaxScaler())])

In [19]:
pipeline

Pipeline(steps=[('Encoder', OrdinalEncoder()), ('Normaliser', MinMaxScaler())])

In [20]:
pipeline.fit_transform(train_set)

array([[0.53358209, 0.5       , 0.5       , ..., 0.69652651, 0.70879121,
        0.67486339],
       [0.05223881, 0.5       , 0.5       , ..., 0.13162706, 0.13003663,
        0.15300546],
       [0.07462687, 0.5       , 0.16666667, ..., 0.17915905, 0.19047619,
        0.19672131],
       ...,
       [0.04477612, 0.75      , 0.83333333, ..., 0.10968921, 0.12087912,
        0.1284153 ],
       [0.07835821, 0.5       , 0.5       , ..., 0.19378428, 0.19413919,
        0.19672131],
       [0.26492537, 0.5       , 0.33333333, ..., 0.45521024, 0.45054945,
        0.43442623]])

### Pipeline composée

<img src="pipeline.png" alt="Texte alternatif" width="450" height="500">


In [21]:
from sklearn.compose import ColumnTransformer 

In [22]:
# définir une liste des variables catégorielles 
categorical_cols = ["cut","color","clarity"]

In [23]:
column_transformer = ColumnTransformer(transformers=[("Encoder",OrdinalEncoder(categories=[cut_order, color_order, clarity_order]),categorical_cols)],
                                       remainder="passthrough")
#Intégrer column_transformer dans une pipeline
pipeline = Pipeline(steps=[("Encoder",column_transformer),
                           ("Scaler",MinMaxScaler())
                          ])
pipeline.fit_transform(train_set)

array([[1.        , 0.5       , 0.57142857, ..., 0.70391061, 0.12903226,
        0.14716981],
       [1.        , 0.5       , 0.42857143, ..., 0.41620112, 0.075382  ,
        0.08710692],
       [1.        , 0.83333333, 0.71428571, ..., 0.44040968, 0.08098472,
        0.09213836],
       ...,
       [0.75      , 0.16666667, 0.57142857, ..., 0.40502793, 0.07453311,
        0.08427673],
       [1.        , 0.5       , 1.        , ..., 0.44785847, 0.08132428,
        0.09213836],
       [1.        , 0.66666667, 0.14285714, ..., 0.58100559, 0.10509338,
        0.11949686]])

In [24]:
pipeline.transform(test_set)

array([[1.        , 0.33333333, 0.14285714, ..., 0.61545624, 0.11290323,
        0.12924528],
       [1.        , 0.33333333, 0.28571429, ..., 0.64804469, 0.11765705,
        0.13679245],
       [0.75      , 0.16666667, 0.28571429, ..., 0.6405959 , 0.11544992,
        0.13144654],
       ...,
       [0.5       , 0.66666667, 0.14285714, ..., 0.60800745, 0.11035654,
        0.12987421],
       [1.        , 0.5       , 0.85714286, ..., 0.59962756, 0.1098472 ,
        0.12484277],
       [0.25      , 0.83333333, 0.71428571, ..., 0.46275605, 0.08488964,
        0.10157233]])

### Exercice : Création des pipelines
<img src="./pipelineImage/pipe1.png" width="200">

In [25]:
from sklearn.feature_selection import SelectKBest, f_regression, f_classif
pipeNiveau1 = Pipeline(steps=[
    ("FeatureEngineering",PolynomialFeatures(degree = 2, include_bias=True)),
    ("SelectFeatures", SelectKBest(score_func=f_regression, k=5)),
    ("Normalisation",MinMaxScaler())])
pipeNiveau1

Pipeline(steps=[('FeatureEngineering', PolynomialFeatures()),
                ('SelectFeatures',
                 SelectKBest(k=5,
                             score_func=<function f_regression at 0x000001F322475A80>)),
                ('Normalisation', MinMaxScaler())])

In [26]:
# Création d’un jeu de données de régression pour tester la pipeline
from sklearn.datasets import make_regression
X, y =make_regression (n_samples = 100, n_features = 4, noise = 0.1, random_state = 42)
pipeNiveau1.fit_transform(X,y)

array([[6.03262586e-01, 3.69231960e-01, 0.00000000e+00, 2.56728701e-01,
        2.33507240e-03],
       [3.17470504e-01, 2.30020341e-01, 5.31391733e-01, 2.82829305e-01,
        2.61159206e-02],
       [1.79406459e-01, 3.63601033e-01, 2.62980978e-01, 1.97733130e-01,
        1.58498975e-03],
       [5.01996265e-01, 3.56237034e-01, 3.41204541e-01, 2.36055325e-01,
        8.21851895e-04],
       [1.68098199e-01, 3.05211385e-01, 3.56230227e-01, 2.67861072e-01,
        2.31513390e-03],
       [6.06092365e-01, 3.17413318e-01, 2.84027264e-01, 2.11196626e-01,
        8.79832415e-04],
       [3.72361791e-01, 3.82066750e-01, 5.34877701e-01, 2.17912274e-01,
        4.58419083e-03],
       [5.31328384e-01, 1.75804281e-01, 1.49194213e-01, 1.43762821e-01,
        5.92457930e-02],
       [1.18406659e-01, 1.22477246e-01, 4.08446003e-01, 5.43306317e-01,
        1.04885300e-01],
       [2.59194826e-01, 5.02191890e-01, 8.01024303e-01, 9.89395779e-02,
        6.19867159e-02],
       [2.50496227e-01, 3.6869

In [27]:
#Création d’un jeu de données de régression pour tester la deuxième pipeline
np.random.seed(42)
n_samples = 100
X_numeric = np.random.rand(n_samples, 2) # 2 variables numériques
X_categorical = np.random.choice(['Paris','Marseille','Belfort'],size=(n_samples, 1))
df = pd.DataFrame(np.hstack((X_numeric,X_categorical)),columns=["X1","X2","Ville"])
df

,X1,X2,Ville
0,0.3745401188473625,0.9507143064099162,Belfort
1,0.7319939418114051,0.5986584841970366,Paris
2,0.15601864044243652,0.15599452033620265,Marseille
3,0.05808361216819946,0.8661761457749352,Marseille
4,0.6011150117432088,0.7080725777960455,Belfort
...,...,...,...
95,0.09310276780589921,0.8972157579533268,Marseille
96,0.9004180571633305,0.6331014572732679,Belfort
97,0.3390297910487007,0.3492095746126609,Paris
98,0.7259556788702394,0.8971102599525771,Marseille


<img src="./pipelineImage/pipe2.png" width="300">

In [28]:
column_transformer = ColumnTransformer(remainder='passthrough',
                  transformers=[('Encoder des villes ', OneHotEncoder(),
                                 ['Ville'])])
#Intégrer column_transformer dans une pipeline
pipeNiveau2 = Pipeline(steps=[("Encoder",column_transformer),
                             ("FeatureEngineering",PolynomialFeatures(degree = 2, include_bias=False)),
                               ("Normalisation",MinMaxScaler())

                          ])

pipeNiveau2

Pipeline(steps=[('Encoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Encoder des villes ',
                                                  OneHotEncoder(),
                                                  ['Ville'])])),
                ('FeatureEngineering', PolynomialFeatures(include_bias=False)),
                ('Normalisation', MinMaxScaler())])

In [29]:
pipeNiveau2.fit_transform(df).shape

(100, 20)

<img src="./pipelineImage/pipe3.png" width="350">

In [30]:
np.random.seed(42)
n_samples = 100
X_numeric = np.random.rand(n_samples, 2) # 2 variables numérique
X_categorical = np.random.choice(['A','B','C','D'],size = (n_samples,2)) # 2 variables catégorielles
y=np.random.rand(n_samples)*10 # variable cible
#création d'un DataFrame
df=pd.DataFrame(np.hstack((X_numeric,X_categorical)), columns=["X1","X2","Cat 1","Cat 2"])
df["y"]= y
#Définition des colonnes catégorielles
cat_cols = ["Cat 1","Cat 2"]
df['Cat 2']

0     D
1     A
2     D
3     D
4     B
     ..
95    D
96    D
97    D
98    C
99    B
Name: Cat 2, Length: 100, dtype: object

In [ ]:
column_transformer = ColumnTransformer(remainder='passthrough',
                  transformers=[('Encoder des animales ', OneHotEncoder(), ['Cat1','Cat2'])])
#Intégrer column_transformer dans une pipeline
pipelineNiveau3 = Pipeline(steps=[("Encoder",column_transformer),
                                   ("SelectFeatures", SelectKBest(score_func=f_regression, k=2)),
                             ("FeatureEngineering",PolynomialFeatures(degree = 2, include_bias=False)),
                               ("Normalisation",MinMaxScaler())

                          ])

pipelineNiveau3



Pipeline(steps=[('Encoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Encoder des animales ',
                                                  OneHotEncoder(),
                                                  ['Cat1', 'Cat2'])])),
                ('SelectFeatures',
                 SelectKBest(k=2,
                             score_func=<function f_regression at 0x000001F322475A80>)),
                ('FeatureEngineering', PolynomialFeatures(include_bias=False)),
                ('Normalisation', MinMaxScaler())])

In [32]:
df

,X1,X2,Cat 1,Cat 2,y
0,0.3745401188473625,0.9507143064099162,D,D,0.516817
1,0.7319939418114051,0.5986584841970366,C,A,5.313546
2,0.15601864044243652,0.15599452033620265,D,D,5.406351
3,0.05808361216819946,0.8661761457749352,B,D,6.374299
4,0.6011150117432088,0.7080725777960455,D,B,7.260913
...,...,...,...,...,...
95,0.09310276780589921,0.8972157579533268,A,D,9.307573
96,0.9004180571633305,0.6331014572732679,A,D,8.584128
97,0.3390297910487007,0.3492095746126609,D,D,4.289940
98,0.7259556788702394,0.8971102599525771,A,C,7.508711


<img src="./pipelineImage/pipe4.png" width="350">